name: ðŸš€ On push to main

on:
  push:
    branches:
      - main
    # paths:
    #   - "services/emotion-ingestion-service/**"

permissions:
  contents: read
  packages: write

jobs:
  tag:
    name: ðŸ”– Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image-emotion-ingestion-service:
    name: ðŸ³ Build and Push Docker Image - Emotion Ingestion Service
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .env file from secrets
        run: cp services/emotion-ingestion-service/.env.example services/emotion-ingestion-service/.env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./services/emotion-ingestion-service
          push: true
          file: ./services/emotion-ingestion-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/diogomassis/empathic-credit-system/emotion-ingestion-service:${{ steps.get_tag.outputs.tag }}
            ghcr.io/diogomassis/empathic-credit-system/emotion-ingestion-service:latest
